import React,{useState} from 'react';
import {useApp,Button,Field,Money,Modal,Qty,Summary,BuyerPicker} from './ui';
import {uid,today,yen,stockRemaining} from './domain';
import {delivery,marketTotals,possibleSets,sellBundle} from './commerce';
export function Markets({roundId=null}){
 const {state}=useApp();const [edit,setEdit]=useState(null),[selected,setSelected]=useState(null),[bundle,setBundle]=useState(false),[selling,setSelling]=useState(null);
 const m=state.markets.find(m=>m.id===selected),totals=m?marketTotals(state,m):null;
 return <section className="sales-tools"><div className="section-head"><h2>販売場所・セット</h2><Button secondary onClick={()=>setEdit({})}>＋ 販売場所を登録</Button></div><p className="muted">通常の単品販売は、場所を登録しなくても完了できます。セット販売や場所代を記録するときだけ使います。</p>{!m?state.markets.filter(m=>!roundId||m.roundId===roundId).map(m=><Button secondary key={m.id} onClick={()=>setSelected(m.id)}>{m.date} ／ {m.name} ／ 売上 {yen(marketTotals(state,m).revenue)}</Button>):<>
 <Button secondary onClick={()=>setSelected(null)}>‹ 販売イベント一覧</Button><div className="section-head"><h2>{m.name}</h2><Button secondary onClick={()=>setEdit(m)}>場所・経費を編集</Button></div><p>{m.date} ／ {m.place||'場所未入力'} ／ 納品 {state.rounds.find(r=>r.id===m.roundId)?.date}</p><div className="grid2"><Summary label="売上" value={yen(totals.revenue)}/><Summary label="商品仕入原価（売れた分）" value={yen(totals.cost)}/><Summary label="商品販売利益" value={yen(totals.baseProfit)}/><Summary label={`最終利益${totals.expenseUnknown?'（場所代不明・暫定）':''}`} value={yen(totals.profit)}/></div><p className="notice">{m.expense==null?'場所代・出店経費は不明／未反映。0円と確定したものではありません。':m.expenseMode==='apply'?`出店経費 ${yen(m.expense)} を利益から差し引きます。`:`出店経費 ${yen(m.expense)} は参考情報のみ。利益からは差し引きません。`}</p>
 <div className="section-head"><h2>セット販売</h2><Button onClick={()=>setBundle(true)}>＋ セットを作る</Button></div>
 {state.bundles.filter(b=>b.marketId===m.id).map(b=><section className="card" key={b.id}><h3>{b.name} ／ {yen(b.price)}</h3><p>あと {possibleSets(state,b)} セット販売できます ／ 販売済み {state.bundleSales.filter(x=>!x.void&&x.bundleId===b.id).reduce((n,x)=>n+x.qty,0)} セット</p>{b.components.map(c=><p key={c.stockId}>{state.stocks.find(st=>st.id===c.stockId)?.name} ×{c.qty} ／ 残数 {stockRemaining(state,state.stocks.find(st=>st.id===c.stockId))}</p>)}<Button disabled={possibleSets(state,b)<1} onClick={()=>setSelling(b)}>セット販売を記録</Button></section>)}
 <details><summary>セットの販売履歴</summary>{state.bundleSales.filter(x=>x.marketId===m.id).map(x=><div className="card" key={x.id}>{x.date} {x.name} ×{x.qty} ／ {yen(x.price*x.qty)} ／ {x.destinationType==='buyer'?'個人請求':x.destinationType==='unknown'?'販売先・支払未確認':x.paymentStatus==='paid'?'入金済み':'入金未確認'}{x.destinationName?`（${x.destinationName}）`:''}{x.void?'（取消）':<Button secondary danger onClick={()=>{if(confirm('セット販売を取り消し、構成商品の残数を戻しますか？'))save(s=>{s.bundleSales.find(a=>a.id===x.id).void=true;},'セット販売取消');}}>取消</Button>}</div>)}</details></>}
 {edit&&<MarketEditor value={edit.id?edit:null} roundId={roundId} onClose={()=>setEdit(null)} onCreated={setSelected}/>}
 {bundle&&m&&<BundleEditor market={m} onClose={()=>setBundle(false)}/>}
 {selling&&<BundleSale market={m} bundle={selling} onClose={()=>setSelling(null)}/>} 
 </section>;
}
function BundleSale({market,bundle,onClose}){
 const {state,save}=useApp();const [qty,setQty]=useState(1),[entry,set]=useState({destinationType:'external',paymentStatus:'unconfirmed',destinationName:market.name,buyerId:'',note:''});
 return <Modal title="セット販売を記録" onClose={onClose}><h3>{bundle.name} ／ 1セット {yen(bundle.price)}</h3><Qty label="販売セット数" value={qty} onChange={setQty}/><h3>販売先</h3><div className="choice-grid"><Button secondary={entry.destinationType!=='external'} onClick={()=>set({...entry,destinationType:'external',paymentStatus:'unconfirmed'})}>外部販売</Button><Button secondary={entry.destinationType!=='buyer'} onClick={()=>set({...entry,destinationType:'buyer',paymentStatus:'later'})}>登録済み購入者</Button><Button secondary={entry.destinationType!=='unknown'} onClick={()=>set({...entry,destinationType:'unknown',paymentStatus:'unconfirmed'})}>販売先未確認</Button></div>{entry.destinationType==='external'&&<><Field label="販売先・団体・マルシェ名"><input list="bundle-destinations" value={entry.destinationName} onChange={e=>set({...entry,destinationName:e.target.value})}/></Field><datalist id="bundle-destinations">{state.externalDestinations.map(x=><option value={x} key={x}/>)}</datalist><div className="choice-grid"><Button secondary={entry.paymentStatus!=='paid'} onClick={()=>set({...entry,paymentStatus:'paid'})}>入金済み</Button><Button secondary={entry.paymentStatus!=='unconfirmed'} onClick={()=>set({...entry,paymentStatus:'unconfirmed'})}>入金未確認</Button></div></>}{entry.destinationType==='buyer'&&<BuyerPicker value={entry.buyerId} includeTest={state.rounds.find(r=>r.id===market.roundId)?.test} onChange={buyerId=>set({...entry,buyerId})}/>} {entry.destinationType==='unknown'&&<p className="notice">売れた数量だけ記録し、入金・請求は未確認のまま保持します。</p>}<p className="total">売上 {yen(qty*bundle.price)}</p><Field label="支払メモ（任意）"><textarea value={entry.note} onChange={e=>set({...entry,note:e.target.value})}/></Field><p>販売時に構成商品の残数を減らし、仕入原価を引き継ぎます。</p><Button onClick={async()=>{if(await save(s=>sellBundle(s,s.bundles.find(b=>b.id===bundle.id),qty,market.date,entry),'セット販売を記録'))onClose();}}>この内容で販売を記録</Button></Modal>;
}
function MarketEditor({value,roundId,onClose,onCreated}){
 const {state,save}=useApp();const [m,set]=useState(value?structuredClone(value):{id:uid(),name:'',date:today(),place:'',note:'',expense:null,expenseMode:'reference',roundId:roundId||''}),[date,setDate]=useState(today()),[test,setTest]=useState(false);
 const put=(k,v)=>set({...m,[k]:v});
 return <Modal title="販売場所・出店経費" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();if(await save(s=>{if(!m.roundId)m.roundId=delivery(s,date,test).id;const i=s.markets.findIndex(x=>x.id===m.id);if(i<0)s.markets.push(m);else s.markets[i]=m;},'販売場所を保存')){onCreated(m.id);onClose();}}}><Field label="販売場所・催し名" required value={m.name} onChange={e=>put('name',e.target.value)}/><Field label="販売日" required type="date" value={m.date} onChange={e=>put('date',e.target.value)}/><Field label="場所メモ（任意）" value={m.place} onChange={e=>put('place',e.target.value)}/>{!value&&<><Field label="納品回"><select value={m.roundId} onChange={e=>put('roundId',e.target.value)}><option value="">新しい納品日を指定</option>{state.rounds.map(r=><option key={r.id} value={r.id}>{r.date}{r.test?'（テスト）':''}</option>)}</select></Field>{!m.roundId&&<><Field label="納品予定日" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Field label="テスト入力"><input type="checkbox" checked={test} onChange={e=>setTest(e.target.checked)}/></Field></>}</>}
 <Money label="場所代・出店経費（不明なら空欄）" value={m.expense} onChange={v=>put('expense',v)}/><Field label="出店経費の扱い"><select value={m.expenseMode} onChange={e=>put('expenseMode',e.target.value)}><option value="reference">参考情報のみ（わっぱん利益から引かない）</option><option value="apply">わっぱん利益へ反映する</option></select></Field><Field label="メモ・支払メモ"><textarea value={m.note} onChange={e=>put('note',e.target.value)}/></Field><Button type="submit">販売場所を保存</Button></form></Modal>;
}
function BundleEditor({market,onClose}){
 const {state,save}=useApp();const [b,set]=useState({id:uid(),name:'',price:null,marketId:market.id,components:[]});
 return <Modal title="セットを作る" onClose={onClose}><Field label="セット名" value={b.name} onChange={e=>set({...b,name:e.target.value})}/><Money label="1セットの販売価格" value={b.price} onChange={v=>set({...b,price:v})}/><p>この納品日の販売用商品から構成を選びます。販売を記録した時点で共通の残数が減ります。</p>{state.stocks.filter(st=>st.roundId===market.roundId&&!st.cancelled).map(st=><div className="card" key={st.id}><strong>{st.name}</strong><p>残り {stockRemaining(state,st)} ／ 仕入単価 {yen(st.cost)}</p><Qty label={`${st.name} セット必要数`} value={b.components.find(c=>c.stockId===st.id)?.qty||0} onChange={qty=>set({...b,components:[...b.components.filter(c=>c.stockId!==st.id),...(qty?[{stockId:st.id,qty}]:[])]})}/></div>)}<p>作成可能 {possibleSets(state,b)} セット</p><Button onClick={async()=>{if(await save(s=>s.bundles.push(b),'セット構成・価格を保存'))onClose();}}>セットを保存</Button></Modal>;
}
